cd ..
git clone https://github.com/ShiftMediaProject/bzip2 
git clone https://github.com/ShiftMediaProject/enca
git clone https://github.com/ShiftMediaProject/expat
git clone https://github.com/ShiftMediaProject/fdk-aac
git clone https://github.com/ShiftMediaProject/FFmpeg
git clone https://github.com/ShiftMediaProject/FFVS-Project-Generator
git clone https://github.com/ShiftMediaProject/fontconfig
git clone https://github.com/ShiftMediaProject/freetype2
git clone https://github.com/ShiftMediaProject/fribidi
git clone https://github.com/ShiftMediaProject/game-music-emu
git clone https://github.com/ShiftMediaProject/gmp
git clone https://github.com/ShiftMediaProject/gnutls
git clone https://github.com/ShiftMediaProject/harfbuzz
git clone https://github.com/ShiftMediaProject/lame
git clone https://github.com/ShiftMediaProject/libaacs
git clone https://github.com/ShiftMediaProject/libarchive
git clone https://github.com/ShiftMediaProject/libass
git clone https://github.com/ShiftMediaProject/harfbuzz
git clone https://github.com/ShiftMediaProject/libbdplus
git clone https://github.com/ShiftMediaProject/libbluray
git clone https://github.com/ShiftMediaProject/libcdio
git clone https://github.com/ShiftMediaProject/libcdio-paranoia
git clone https://github.com/ShiftMediaProject/libdvdcss
git clone https://github.com/ShiftMediaProject/libdvdnav
git clone https://github.com/ShiftMediaProject/libdvdread
git clone https://github.com/ShiftMediaProject/libgcrypt
git clone https://github.com/ShiftMediaProject/libgpg-error
git clone https://github.com/ShiftMediaProject/libiconv
git clone https://github.com/ShiftMediaProject/libilbc
git clone https://github.com/ShiftMediaProject/liblzma
git clone https://github.com/ShiftMediaProject/libssh
git clone https://github.com/ShiftMediaProject/libvpx
git clone https://github.com/ShiftMediaProject/libxml2
git clone https://github.com/ShiftMediaProject/mfx_dispatch
git clone https://github.com/ShiftMediaProject/modplug
git clone https://github.com/ShiftMediaProject/mpv
git clone https://github.com/ShiftMediaProject/nettle
git clone https://github.com/ShiftMediaProject/ogg
git clone https://github.com/ShiftMediaProject/openssl
git clone https://github.com/ShiftMediaProject/opus
git clone https://github.com/ShiftMediaProject/PortAudio
git clone https://github.com/ShiftMediaProject/rtmpdump
git clone https://github.com/ShiftMediaProject/SDL
git clone https://github.com/ShiftMediaProject/ShiftMediaProject.github.io
git clone https://github.com/ShiftMediaProject/soxr
git clone https://github.com/ShiftMediaProject/speex
git clone https://github.com/ShiftMediaProject/theora
git clone https://github.com/ShiftMediaProject/vorbis
git clone https://github.com/ShiftMediaProject/VSNASM
git clone https://github.com/ShiftMediaProject/VSYASM
git clone https://github.com/ShiftMediaProject/x264
git clone https://github.com/ShiftMediaProject/x265
git clone https://github.com/ShiftMediaProject/xvid
git clone https://github.com/ShiftMediaProject/zlib
cd -
